### ISSUE TITLE
Inaccurate result

### ISSUE THREAD

**Issue by jrivers96** [Paradigm4/fast_count#2]
Calling fast_count can lead to an inaccurate result when the chunk map is being modified, but should give order of magnitude results...

**Comment by apoliakov** [comment]
Array locking by version should prevent this from happening -- has this been experimentally reproduced?

**Comment by jrivers96** [comment]
No, it has not been reproduced yet. Array locks aren't taken on the chunkmap.  We could do this within the UDO.  

I also need to look into replicated arrays.

**Comment by jrivers96** [comment]
0.
iquery  -aq "store(build(<v:double>[i=0:1000,100,0], i), XXX)"

1. 
iquery  -aq "list('arrays', true)"
{No} name,uaid,aid,schema,availability,temporary
{0} 'XXX',271,271,'XXX<v:double> [i=0:1000,100,0]',true,false
{1} 'XXX@1',271,272,'XXX@1<v:double> [i=0:1000,100,0]',true,false

2.
iquery  -aq "aggregate(project(filter(list('chunk map'), inst=instn and attid=0 and uaid=271 and arrid <= 272), nelem), sum(nelem))"
{i} nelem_sum
{0} 1001

You can/should combine step 1 & 2 with a cross_join or smth (and make it a macro :)

2c

**Comment by apoliakov** [comment]
Yeah -- you're right that the locks aren't taken on the chunk map. But your code doesn't work on the chunk map either... You get chunks from the ArrayIterator - which means the array is locked and you're accessing chunks for a specific version and they're not replicas.
