### ISSUE TITLE
Faced a problem while installing this with devtools

### ISSUE THREAD

**Issue by ksens** [Paradigm4/fast_count#4]
got some errors while installing this repo with `devtools`

```
scidb@ip-172-31-18-59:~$ iquery -aq "install_github('paradigm4/fast_count')"
SystemException in file: Physicalinstall_github.cpp function: execute line: 118
Error id: scidb::SCIDB_SE_OPERATOR::SCIDB_LE_ILLEGAL_OPERATION
Error description: Operator error. Illegal operation: failed to build plugin.
```

**Comment by jrivers96** [comment]
You probably need to install g++ 4.9 and associated packages.  The shim repository has a line that designates the packages that you need to install to build. dev_tools attempts to build the package from source and gives the above error when it fails. 

I have also included what I think are the packages necessary in the fast_count repo.
